# Generated by Django 3.2.18 on 2023-05-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='')),
                ('due_date', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('None', 'Pending'), ('1', 'To do'), ('2', 'In pregress'), ('3', 'Completed')], default='1', max_length=4)),
            ],
        ),
    ]
